### ISSUE TITLE
From where do I know, which one is TX and RX?

### ISSUE THREAD

**Issue by sandmen** [jeanleflambeur/esp8266_bridge_broadcast#1]
Hi, want to try the application.
How do I switch tx&rx function ?

Thanks

**Comment by jeanleflambeur** [comment]
There is no switch. The program works both as RX and TX. It takes everything that it received in stdin and sends it, and whatever it receives it outputs on stdout.
So if you want a node to be RX only, don't send anything to stdin :)

You can test if everything works ok by using a small MTU (say 16 bytes) and starting 2 instances of the program, each with its own ESP connected.
Then type some text into one (at least 16 characters, >= MTU) and press enter. The other node should display the text.
